// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc_configs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ipc_5fconfigs_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ipc_5fconfigs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024002 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ipc_5fconfigs_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ipc_5fconfigs_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ipc_5fconfigs_2eproto;
class BEV_bounding_box_cord_request;
struct BEV_bounding_box_cord_requestDefaultTypeInternal;
extern BEV_bounding_box_cord_requestDefaultTypeInternal _BEV_bounding_box_cord_request_default_instance_;
class empty_return;
struct empty_returnDefaultTypeInternal;
extern empty_returnDefaultTypeInternal _empty_return_default_instance_;
class image_request;
struct image_requestDefaultTypeInternal;
extern image_requestDefaultTypeInternal _image_request_default_instance_;
class request_data;
struct request_dataDefaultTypeInternal;
extern request_dataDefaultTypeInternal _request_data_default_instance_;
class transform_request;
struct transform_requestDefaultTypeInternal;
extern transform_requestDefaultTypeInternal _transform_request_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class request_data final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_data) */ {
 public:
  inline request_data() : request_data(nullptr) {}
  ~request_data() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR request_data(::google::protobuf::internal::ConstantInitialized);

  request_data(const request_data& from);
  request_data(request_data&& from) noexcept
    : request_data() {
    *this = ::std::move(from);
  }

  inline request_data& operator=(const request_data& from) {
    CopyFrom(from);
    return *this;
  }
  inline request_data& operator=(request_data&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const request_data& default_instance() {
    return *internal_default_instance();
  }
  static inline const request_data* internal_default_instance() {
    return reinterpret_cast<const request_data*>(
               &_request_data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(request_data& a, request_data& b) {
    a.Swap(&b);
  }
  inline void Swap(request_data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(request_data* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  request_data* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<request_data>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const request_data& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const request_data& from) {
    request_data::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(request_data* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "request_data";
  }
  protected:
  explicit request_data(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageDataFieldNumber = 1,
    kCarTransformFieldNumber = 2,
    kBEVBoundingBoxCordFieldNumber = 3,
  };
  // .image_request image_data = 1;
  bool has_image_data() const;
  void clear_image_data() ;
  const ::image_request& image_data() const;
  PROTOBUF_NODISCARD ::image_request* release_image_data();
  ::image_request* mutable_image_data();
  void set_allocated_image_data(::image_request* value);
  void unsafe_arena_set_allocated_image_data(::image_request* value);
  ::image_request* unsafe_arena_release_image_data();

  private:
  const ::image_request& _internal_image_data() const;
  ::image_request* _internal_mutable_image_data();

  public:
  // .transform_request car_transform = 2;
  bool has_car_transform() const;
  void clear_car_transform() ;
  const ::transform_request& car_transform() const;
  PROTOBUF_NODISCARD ::transform_request* release_car_transform();
  ::transform_request* mutable_car_transform();
  void set_allocated_car_transform(::transform_request* value);
  void unsafe_arena_set_allocated_car_transform(::transform_request* value);
  ::transform_request* unsafe_arena_release_car_transform();

  private:
  const ::transform_request& _internal_car_transform() const;
  ::transform_request* _internal_mutable_car_transform();

  public:
  // .BEV_bounding_box_cord_request BEV_bounding_box_cord = 3;
  bool has_bev_bounding_box_cord() const;
  void clear_bev_bounding_box_cord() ;
  const ::BEV_bounding_box_cord_request& bev_bounding_box_cord() const;
  PROTOBUF_NODISCARD ::BEV_bounding_box_cord_request* release_bev_bounding_box_cord();
  ::BEV_bounding_box_cord_request* mutable_bev_bounding_box_cord();
  void set_allocated_bev_bounding_box_cord(::BEV_bounding_box_cord_request* value);
  void unsafe_arena_set_allocated_bev_bounding_box_cord(::BEV_bounding_box_cord_request* value);
  ::BEV_bounding_box_cord_request* unsafe_arena_release_bev_bounding_box_cord();

  private:
  const ::BEV_bounding_box_cord_request& _internal_bev_bounding_box_cord() const;
  ::BEV_bounding_box_cord_request* _internal_mutable_bev_bounding_box_cord();

  public:
  // @@protoc_insertion_point(class_scope:request_data)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3, 3, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::image_request* image_data_;
    ::transform_request* car_transform_;
    ::BEV_bounding_box_cord_request* bev_bounding_box_cord_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class image_request final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:image_request) */ {
 public:
  inline image_request() : image_request(nullptr) {}
  ~image_request() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR image_request(::google::protobuf::internal::ConstantInitialized);

  image_request(const image_request& from);
  image_request(image_request&& from) noexcept
    : image_request() {
    *this = ::std::move(from);
  }

  inline image_request& operator=(const image_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline image_request& operator=(image_request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const image_request& default_instance() {
    return *internal_default_instance();
  }
  static inline const image_request* internal_default_instance() {
    return reinterpret_cast<const image_request*>(
               &_image_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(image_request& a, image_request& b) {
    a.Swap(&b);
  }
  inline void Swap(image_request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(image_request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  image_request* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<image_request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const image_request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const image_request& from) {
    image_request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(image_request* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "image_request";
  }
  protected:
  explicit image_request(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated float data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::google::protobuf::RepeatedField<float>& data() const;
  ::google::protobuf::RepeatedField<float>* mutable_data();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_data() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:image_request)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedField<float> data_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class transform_request final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:transform_request) */ {
 public:
  inline transform_request() : transform_request(nullptr) {}
  ~transform_request() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR transform_request(::google::protobuf::internal::ConstantInitialized);

  transform_request(const transform_request& from);
  transform_request(transform_request&& from) noexcept
    : transform_request() {
    *this = ::std::move(from);
  }

  inline transform_request& operator=(const transform_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline transform_request& operator=(transform_request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const transform_request& default_instance() {
    return *internal_default_instance();
  }
  static inline const transform_request* internal_default_instance() {
    return reinterpret_cast<const transform_request*>(
               &_transform_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(transform_request& a, transform_request& b) {
    a.Swap(&b);
  }
  inline void Swap(transform_request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(transform_request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  transform_request* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<transform_request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const transform_request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const transform_request& from) {
    transform_request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(transform_request* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "transform_request";
  }
  protected:
  explicit transform_request(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kPitchFieldNumber = 4,
    kYawFieldNumber = 5,
    kRollFieldNumber = 6,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // float pitch = 4;
  void clear_pitch() ;
  float pitch() const;
  void set_pitch(float value);

  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);

  public:
  // float yaw = 5;
  void clear_yaw() ;
  float yaw() const;
  void set_yaw(float value);

  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);

  public:
  // float roll = 6;
  void clear_roll() ;
  float roll() const;
  void set_roll(float value);

  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);

  public:
  // @@protoc_insertion_point(class_scope:transform_request)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    float pitch_;
    float yaw_;
    float roll_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class BEV_bounding_box_cord_request final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BEV_bounding_box_cord_request) */ {
 public:
  inline BEV_bounding_box_cord_request() : BEV_bounding_box_cord_request(nullptr) {}
  ~BEV_bounding_box_cord_request() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BEV_bounding_box_cord_request(::google::protobuf::internal::ConstantInitialized);

  BEV_bounding_box_cord_request(const BEV_bounding_box_cord_request& from);
  BEV_bounding_box_cord_request(BEV_bounding_box_cord_request&& from) noexcept
    : BEV_bounding_box_cord_request() {
    *this = ::std::move(from);
  }

  inline BEV_bounding_box_cord_request& operator=(const BEV_bounding_box_cord_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline BEV_bounding_box_cord_request& operator=(BEV_bounding_box_cord_request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BEV_bounding_box_cord_request& default_instance() {
    return *internal_default_instance();
  }
  static inline const BEV_bounding_box_cord_request* internal_default_instance() {
    return reinterpret_cast<const BEV_bounding_box_cord_request*>(
               &_BEV_bounding_box_cord_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BEV_bounding_box_cord_request& a, BEV_bounding_box_cord_request& b) {
    a.Swap(&b);
  }
  inline void Swap(BEV_bounding_box_cord_request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BEV_bounding_box_cord_request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BEV_bounding_box_cord_request* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BEV_bounding_box_cord_request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BEV_bounding_box_cord_request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const BEV_bounding_box_cord_request& from) {
    BEV_bounding_box_cord_request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BEV_bounding_box_cord_request* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "BEV_bounding_box_cord_request";
  }
  protected:
  explicit BEV_bounding_box_cord_request(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeftBottomXFieldNumber = 1,
    kLeftBottomYFieldNumber = 2,
    kLeftTopXFieldNumber = 3,
    kLeftTopYFieldNumber = 4,
    kRightTopXFieldNumber = 5,
    kRightTopYFieldNumber = 6,
    kRightBottomXFieldNumber = 7,
    kRightBottomYFieldNumber = 8,
  };
  // float left_bottom_x = 1;
  void clear_left_bottom_x() ;
  float left_bottom_x() const;
  void set_left_bottom_x(float value);

  private:
  float _internal_left_bottom_x() const;
  void _internal_set_left_bottom_x(float value);

  public:
  // float left_bottom_y = 2;
  void clear_left_bottom_y() ;
  float left_bottom_y() const;
  void set_left_bottom_y(float value);

  private:
  float _internal_left_bottom_y() const;
  void _internal_set_left_bottom_y(float value);

  public:
  // float left_top_x = 3;
  void clear_left_top_x() ;
  float left_top_x() const;
  void set_left_top_x(float value);

  private:
  float _internal_left_top_x() const;
  void _internal_set_left_top_x(float value);

  public:
  // float left_top_y = 4;
  void clear_left_top_y() ;
  float left_top_y() const;
  void set_left_top_y(float value);

  private:
  float _internal_left_top_y() const;
  void _internal_set_left_top_y(float value);

  public:
  // float right_top_x = 5;
  void clear_right_top_x() ;
  float right_top_x() const;
  void set_right_top_x(float value);

  private:
  float _internal_right_top_x() const;
  void _internal_set_right_top_x(float value);

  public:
  // float right_top_y = 6;
  void clear_right_top_y() ;
  float right_top_y() const;
  void set_right_top_y(float value);

  private:
  float _internal_right_top_y() const;
  void _internal_set_right_top_y(float value);

  public:
  // float right_bottom_x = 7;
  void clear_right_bottom_x() ;
  float right_bottom_x() const;
  void set_right_bottom_x(float value);

  private:
  float _internal_right_bottom_x() const;
  void _internal_set_right_bottom_x(float value);

  public:
  // float right_bottom_y = 8;
  void clear_right_bottom_y() ;
  float right_bottom_y() const;
  void set_right_bottom_y(float value);

  private:
  float _internal_right_bottom_y() const;
  void _internal_set_right_bottom_y(float value);

  public:
  // @@protoc_insertion_point(class_scope:BEV_bounding_box_cord_request)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float left_bottom_x_;
    float left_bottom_y_;
    float left_top_x_;
    float left_top_y_;
    float right_top_x_;
    float right_top_y_;
    float right_bottom_x_;
    float right_bottom_y_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class empty_return final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:empty_return) */ {
 public:
  inline empty_return() : empty_return(nullptr) {}
  ~empty_return() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR empty_return(::google::protobuf::internal::ConstantInitialized);

  empty_return(const empty_return& from);
  empty_return(empty_return&& from) noexcept
    : empty_return() {
    *this = ::std::move(from);
  }

  inline empty_return& operator=(const empty_return& from) {
    CopyFrom(from);
    return *this;
  }
  inline empty_return& operator=(empty_return&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const empty_return& default_instance() {
    return *internal_default_instance();
  }
  static inline const empty_return* internal_default_instance() {
    return reinterpret_cast<const empty_return*>(
               &_empty_return_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(empty_return& a, empty_return& b) {
    a.Swap(&b);
  }
  inline void Swap(empty_return* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(empty_return* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  empty_return* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<empty_return>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const empty_return& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const empty_return& from) {
    empty_return::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(empty_return* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "empty_return";
  }
  protected:
  explicit empty_return(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // float result = 1;
  void clear_result() ;
  float result() const;
  void set_result(float value);

  private:
  float _internal_result() const;
  void _internal_set_result(float value);

  public:
  // @@protoc_insertion_point(class_scope:empty_return)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float result_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// request_data

// .image_request image_data = 1;
inline bool request_data::has_image_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.image_data_ != nullptr);
  return value;
}
inline void request_data::clear_image_data() {
  if (_impl_.image_data_ != nullptr) _impl_.image_data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::image_request& request_data::_internal_image_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::image_request* p = _impl_.image_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::image_request&>(::_image_request_default_instance_);
}
inline const ::image_request& request_data::image_data() const {
  // @@protoc_insertion_point(field_get:request_data.image_data)
  return _internal_image_data();
}
inline void request_data::unsafe_arena_set_allocated_image_data(::image_request* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.image_data_);
  }
  _impl_.image_data_ = reinterpret_cast<::image_request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request_data.image_data)
}
inline ::image_request* request_data::release_image_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::image_request* released = _impl_.image_data_;
  _impl_.image_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::image_request* request_data::unsafe_arena_release_image_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:request_data.image_data)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::image_request* temp = _impl_.image_data_;
  _impl_.image_data_ = nullptr;
  return temp;
}
inline ::image_request* request_data::_internal_mutable_image_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.image_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::image_request>(GetArenaForAllocation());
    _impl_.image_data_ = reinterpret_cast<::image_request*>(p);
  }
  return _impl_.image_data_;
}
inline ::image_request* request_data::mutable_image_data() {
  ::image_request* _msg = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:request_data.image_data)
  return _msg;
}
inline void request_data::set_allocated_image_data(::image_request* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::image_request*>(_impl_.image_data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::image_request*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.image_data_ = reinterpret_cast<::image_request*>(value);
  // @@protoc_insertion_point(field_set_allocated:request_data.image_data)
}

// .transform_request car_transform = 2;
inline bool request_data::has_car_transform() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.car_transform_ != nullptr);
  return value;
}
inline void request_data::clear_car_transform() {
  if (_impl_.car_transform_ != nullptr) _impl_.car_transform_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::transform_request& request_data::_internal_car_transform() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::transform_request* p = _impl_.car_transform_;
  return p != nullptr ? *p : reinterpret_cast<const ::transform_request&>(::_transform_request_default_instance_);
}
inline const ::transform_request& request_data::car_transform() const {
  // @@protoc_insertion_point(field_get:request_data.car_transform)
  return _internal_car_transform();
}
inline void request_data::unsafe_arena_set_allocated_car_transform(::transform_request* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.car_transform_);
  }
  _impl_.car_transform_ = reinterpret_cast<::transform_request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request_data.car_transform)
}
inline ::transform_request* request_data::release_car_transform() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::transform_request* released = _impl_.car_transform_;
  _impl_.car_transform_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::transform_request* request_data::unsafe_arena_release_car_transform() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:request_data.car_transform)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::transform_request* temp = _impl_.car_transform_;
  _impl_.car_transform_ = nullptr;
  return temp;
}
inline ::transform_request* request_data::_internal_mutable_car_transform() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.car_transform_ == nullptr) {
    auto* p = CreateMaybeMessage<::transform_request>(GetArenaForAllocation());
    _impl_.car_transform_ = reinterpret_cast<::transform_request*>(p);
  }
  return _impl_.car_transform_;
}
inline ::transform_request* request_data::mutable_car_transform() {
  ::transform_request* _msg = _internal_mutable_car_transform();
  // @@protoc_insertion_point(field_mutable:request_data.car_transform)
  return _msg;
}
inline void request_data::set_allocated_car_transform(::transform_request* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::transform_request*>(_impl_.car_transform_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::transform_request*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.car_transform_ = reinterpret_cast<::transform_request*>(value);
  // @@protoc_insertion_point(field_set_allocated:request_data.car_transform)
}

// .BEV_bounding_box_cord_request BEV_bounding_box_cord = 3;
inline bool request_data::has_bev_bounding_box_cord() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.bev_bounding_box_cord_ != nullptr);
  return value;
}
inline void request_data::clear_bev_bounding_box_cord() {
  if (_impl_.bev_bounding_box_cord_ != nullptr) _impl_.bev_bounding_box_cord_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::BEV_bounding_box_cord_request& request_data::_internal_bev_bounding_box_cord() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::BEV_bounding_box_cord_request* p = _impl_.bev_bounding_box_cord_;
  return p != nullptr ? *p : reinterpret_cast<const ::BEV_bounding_box_cord_request&>(::_BEV_bounding_box_cord_request_default_instance_);
}
inline const ::BEV_bounding_box_cord_request& request_data::bev_bounding_box_cord() const {
  // @@protoc_insertion_point(field_get:request_data.BEV_bounding_box_cord)
  return _internal_bev_bounding_box_cord();
}
inline void request_data::unsafe_arena_set_allocated_bev_bounding_box_cord(::BEV_bounding_box_cord_request* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.bev_bounding_box_cord_);
  }
  _impl_.bev_bounding_box_cord_ = reinterpret_cast<::BEV_bounding_box_cord_request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request_data.BEV_bounding_box_cord)
}
inline ::BEV_bounding_box_cord_request* request_data::release_bev_bounding_box_cord() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::BEV_bounding_box_cord_request* released = _impl_.bev_bounding_box_cord_;
  _impl_.bev_bounding_box_cord_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::BEV_bounding_box_cord_request* request_data::unsafe_arena_release_bev_bounding_box_cord() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:request_data.BEV_bounding_box_cord)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::BEV_bounding_box_cord_request* temp = _impl_.bev_bounding_box_cord_;
  _impl_.bev_bounding_box_cord_ = nullptr;
  return temp;
}
inline ::BEV_bounding_box_cord_request* request_data::_internal_mutable_bev_bounding_box_cord() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.bev_bounding_box_cord_ == nullptr) {
    auto* p = CreateMaybeMessage<::BEV_bounding_box_cord_request>(GetArenaForAllocation());
    _impl_.bev_bounding_box_cord_ = reinterpret_cast<::BEV_bounding_box_cord_request*>(p);
  }
  return _impl_.bev_bounding_box_cord_;
}
inline ::BEV_bounding_box_cord_request* request_data::mutable_bev_bounding_box_cord() {
  ::BEV_bounding_box_cord_request* _msg = _internal_mutable_bev_bounding_box_cord();
  // @@protoc_insertion_point(field_mutable:request_data.BEV_bounding_box_cord)
  return _msg;
}
inline void request_data::set_allocated_bev_bounding_box_cord(::BEV_bounding_box_cord_request* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::BEV_bounding_box_cord_request*>(_impl_.bev_bounding_box_cord_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::BEV_bounding_box_cord_request*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.bev_bounding_box_cord_ = reinterpret_cast<::BEV_bounding_box_cord_request*>(value);
  // @@protoc_insertion_point(field_set_allocated:request_data.BEV_bounding_box_cord)
}

// -------------------------------------------------------------------

// image_request

// repeated float data = 1;
inline int image_request::_internal_data_size() const {
  return _internal_data().size();
}
inline int image_request::data_size() const {
  return _internal_data_size();
}
inline void image_request::clear_data() {
  _internal_mutable_data()->Clear();
}
inline float image_request::data(int index) const {
  // @@protoc_insertion_point(field_get:image_request.data)
  return _internal_data().Get(index);
}
inline void image_request::set_data(int index, float value) {
  _internal_mutable_data()->Set(index, value);
  // @@protoc_insertion_point(field_set:image_request.data)
}
inline void image_request::add_data(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_data()->Add(value);
  // @@protoc_insertion_point(field_add:image_request.data)
}
inline const ::google::protobuf::RepeatedField<float>& image_request::data() const {
  // @@protoc_insertion_point(field_list:image_request.data)
  return _internal_data();
}
inline ::google::protobuf::RepeatedField<float>* image_request::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:image_request.data)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_data();
}

inline const ::google::protobuf::RepeatedField<float>& image_request::_internal_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedField<float>* image_request::_internal_mutable_data() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.data_;
}

// -------------------------------------------------------------------

// transform_request

// float x = 1;
inline void transform_request::clear_x() {
  _impl_.x_ = 0;
}
inline float transform_request::x() const {
  // @@protoc_insertion_point(field_get:transform_request.x)
  return _internal_x();
}
inline void transform_request::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:transform_request.x)
}
inline float transform_request::_internal_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.x_;
}
inline void transform_request::_internal_set_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.x_ = value;
}

// float y = 2;
inline void transform_request::clear_y() {
  _impl_.y_ = 0;
}
inline float transform_request::y() const {
  // @@protoc_insertion_point(field_get:transform_request.y)
  return _internal_y();
}
inline void transform_request::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:transform_request.y)
}
inline float transform_request::_internal_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.y_;
}
inline void transform_request::_internal_set_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.y_ = value;
}

// float z = 3;
inline void transform_request::clear_z() {
  _impl_.z_ = 0;
}
inline float transform_request::z() const {
  // @@protoc_insertion_point(field_get:transform_request.z)
  return _internal_z();
}
inline void transform_request::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:transform_request.z)
}
inline float transform_request::_internal_z() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.z_;
}
inline void transform_request::_internal_set_z(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.z_ = value;
}

// float pitch = 4;
inline void transform_request::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float transform_request::pitch() const {
  // @@protoc_insertion_point(field_get:transform_request.pitch)
  return _internal_pitch();
}
inline void transform_request::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:transform_request.pitch)
}
inline float transform_request::_internal_pitch() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.pitch_;
}
inline void transform_request::_internal_set_pitch(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pitch_ = value;
}

// float yaw = 5;
inline void transform_request::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float transform_request::yaw() const {
  // @@protoc_insertion_point(field_get:transform_request.yaw)
  return _internal_yaw();
}
inline void transform_request::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:transform_request.yaw)
}
inline float transform_request::_internal_yaw() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.yaw_;
}
inline void transform_request::_internal_set_yaw(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.yaw_ = value;
}

// float roll = 6;
inline void transform_request::clear_roll() {
  _impl_.roll_ = 0;
}
inline float transform_request::roll() const {
  // @@protoc_insertion_point(field_get:transform_request.roll)
  return _internal_roll();
}
inline void transform_request::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:transform_request.roll)
}
inline float transform_request::_internal_roll() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.roll_;
}
inline void transform_request::_internal_set_roll(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.roll_ = value;
}

// -------------------------------------------------------------------

// BEV_bounding_box_cord_request

// float left_bottom_x = 1;
inline void BEV_bounding_box_cord_request::clear_left_bottom_x() {
  _impl_.left_bottom_x_ = 0;
}
inline float BEV_bounding_box_cord_request::left_bottom_x() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.left_bottom_x)
  return _internal_left_bottom_x();
}
inline void BEV_bounding_box_cord_request::set_left_bottom_x(float value) {
  _internal_set_left_bottom_x(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.left_bottom_x)
}
inline float BEV_bounding_box_cord_request::_internal_left_bottom_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.left_bottom_x_;
}
inline void BEV_bounding_box_cord_request::_internal_set_left_bottom_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.left_bottom_x_ = value;
}

// float left_bottom_y = 2;
inline void BEV_bounding_box_cord_request::clear_left_bottom_y() {
  _impl_.left_bottom_y_ = 0;
}
inline float BEV_bounding_box_cord_request::left_bottom_y() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.left_bottom_y)
  return _internal_left_bottom_y();
}
inline void BEV_bounding_box_cord_request::set_left_bottom_y(float value) {
  _internal_set_left_bottom_y(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.left_bottom_y)
}
inline float BEV_bounding_box_cord_request::_internal_left_bottom_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.left_bottom_y_;
}
inline void BEV_bounding_box_cord_request::_internal_set_left_bottom_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.left_bottom_y_ = value;
}

// float left_top_x = 3;
inline void BEV_bounding_box_cord_request::clear_left_top_x() {
  _impl_.left_top_x_ = 0;
}
inline float BEV_bounding_box_cord_request::left_top_x() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.left_top_x)
  return _internal_left_top_x();
}
inline void BEV_bounding_box_cord_request::set_left_top_x(float value) {
  _internal_set_left_top_x(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.left_top_x)
}
inline float BEV_bounding_box_cord_request::_internal_left_top_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.left_top_x_;
}
inline void BEV_bounding_box_cord_request::_internal_set_left_top_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.left_top_x_ = value;
}

// float left_top_y = 4;
inline void BEV_bounding_box_cord_request::clear_left_top_y() {
  _impl_.left_top_y_ = 0;
}
inline float BEV_bounding_box_cord_request::left_top_y() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.left_top_y)
  return _internal_left_top_y();
}
inline void BEV_bounding_box_cord_request::set_left_top_y(float value) {
  _internal_set_left_top_y(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.left_top_y)
}
inline float BEV_bounding_box_cord_request::_internal_left_top_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.left_top_y_;
}
inline void BEV_bounding_box_cord_request::_internal_set_left_top_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.left_top_y_ = value;
}

// float right_top_x = 5;
inline void BEV_bounding_box_cord_request::clear_right_top_x() {
  _impl_.right_top_x_ = 0;
}
inline float BEV_bounding_box_cord_request::right_top_x() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.right_top_x)
  return _internal_right_top_x();
}
inline void BEV_bounding_box_cord_request::set_right_top_x(float value) {
  _internal_set_right_top_x(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.right_top_x)
}
inline float BEV_bounding_box_cord_request::_internal_right_top_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.right_top_x_;
}
inline void BEV_bounding_box_cord_request::_internal_set_right_top_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.right_top_x_ = value;
}

// float right_top_y = 6;
inline void BEV_bounding_box_cord_request::clear_right_top_y() {
  _impl_.right_top_y_ = 0;
}
inline float BEV_bounding_box_cord_request::right_top_y() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.right_top_y)
  return _internal_right_top_y();
}
inline void BEV_bounding_box_cord_request::set_right_top_y(float value) {
  _internal_set_right_top_y(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.right_top_y)
}
inline float BEV_bounding_box_cord_request::_internal_right_top_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.right_top_y_;
}
inline void BEV_bounding_box_cord_request::_internal_set_right_top_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.right_top_y_ = value;
}

// float right_bottom_x = 7;
inline void BEV_bounding_box_cord_request::clear_right_bottom_x() {
  _impl_.right_bottom_x_ = 0;
}
inline float BEV_bounding_box_cord_request::right_bottom_x() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.right_bottom_x)
  return _internal_right_bottom_x();
}
inline void BEV_bounding_box_cord_request::set_right_bottom_x(float value) {
  _internal_set_right_bottom_x(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.right_bottom_x)
}
inline float BEV_bounding_box_cord_request::_internal_right_bottom_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.right_bottom_x_;
}
inline void BEV_bounding_box_cord_request::_internal_set_right_bottom_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.right_bottom_x_ = value;
}

// float right_bottom_y = 8;
inline void BEV_bounding_box_cord_request::clear_right_bottom_y() {
  _impl_.right_bottom_y_ = 0;
}
inline float BEV_bounding_box_cord_request::right_bottom_y() const {
  // @@protoc_insertion_point(field_get:BEV_bounding_box_cord_request.right_bottom_y)
  return _internal_right_bottom_y();
}
inline void BEV_bounding_box_cord_request::set_right_bottom_y(float value) {
  _internal_set_right_bottom_y(value);
  // @@protoc_insertion_point(field_set:BEV_bounding_box_cord_request.right_bottom_y)
}
inline float BEV_bounding_box_cord_request::_internal_right_bottom_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.right_bottom_y_;
}
inline void BEV_bounding_box_cord_request::_internal_set_right_bottom_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.right_bottom_y_ = value;
}

// -------------------------------------------------------------------

// empty_return

// float result = 1;
inline void empty_return::clear_result() {
  _impl_.result_ = 0;
}
inline float empty_return::result() const {
  // @@protoc_insertion_point(field_get:empty_return.result)
  return _internal_result();
}
inline void empty_return::set_result(float value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:empty_return.result)
}
inline float empty_return::_internal_result() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.result_;
}
inline void empty_return::_internal_set_result(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.result_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ipc_5fconfigs_2eproto_2epb_2eh
