// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ipc_configs.proto
// Original file comments:
// To execute for pytho run: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ipc_configs.proto
// To execute for C++ run: protoc --proto_path=./ --cpp_out=src/build/gens ./ipc_configs.proto
//  protoc --proto_path=./  -I "D:\CARLA_0.9.14\Self-Parking-Car\src\build\protos" --grpc_out=. --plugin=protoc-gen-grpc="D:\CARLA_0.9.14\Self-Parking-Car\src\build\_deps\grpc-build\grpc_cpp_plugin.exe" ./ipc_configs.proto
//
#ifndef GRPC_ipc_5fconfigs_2eproto__INCLUDED
#define GRPC_ipc_5fconfigs_2eproto__INCLUDED

#include "ipc_configs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class image_transfer final {
 public:
  static constexpr char const* service_full_name() {
    return "image_transfer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status send_data(::grpc::ClientContext* context, const ::request_data& request, ::empty_return* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::empty_return>> Asyncsend_data(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::empty_return>>(Asyncsend_dataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::empty_return>> PrepareAsyncsend_data(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::empty_return>>(PrepareAsyncsend_dataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void send_data(::grpc::ClientContext* context, const ::request_data* request, ::empty_return* response, std::function<void(::grpc::Status)>) = 0;
      virtual void send_data(::grpc::ClientContext* context, const ::request_data* request, ::empty_return* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::empty_return>* Asyncsend_dataRaw(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::empty_return>* PrepareAsyncsend_dataRaw(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status send_data(::grpc::ClientContext* context, const ::request_data& request, ::empty_return* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::empty_return>> Asyncsend_data(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::empty_return>>(Asyncsend_dataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::empty_return>> PrepareAsyncsend_data(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::empty_return>>(PrepareAsyncsend_dataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void send_data(::grpc::ClientContext* context, const ::request_data* request, ::empty_return* response, std::function<void(::grpc::Status)>) override;
      void send_data(::grpc::ClientContext* context, const ::request_data* request, ::empty_return* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::empty_return>* Asyncsend_dataRaw(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::empty_return>* PrepareAsyncsend_dataRaw(::grpc::ClientContext* context, const ::request_data& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_send_data_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status send_data(::grpc::ServerContext* context, const ::request_data* request, ::empty_return* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_send_data() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_data(::grpc::ServerContext* context, ::request_data* request, ::grpc::ServerAsyncResponseWriter< ::empty_return>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_send_data<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_send_data() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::request_data, ::empty_return>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::request_data* request, ::empty_return* response) { return this->send_data(context, request, response); }));}
    void SetMessageAllocatorFor_send_data(
        ::grpc::MessageAllocator< ::request_data, ::empty_return>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::request_data, ::empty_return>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* send_data(
      ::grpc::CallbackServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_send_data<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_send_data() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_send_data() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_data(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_send_data() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->send_data(context, request, response); }));
    }
    ~WithRawCallbackMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* send_data(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_send_data() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::request_data, ::empty_return>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::request_data, ::empty_return>* streamer) {
                       return this->Streamedsend_data(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_data(::grpc::ServerContext* /*context*/, const ::request_data* /*request*/, ::empty_return* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_data(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::request_data,::empty_return>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_send_data<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_send_data<Service > StreamedService;
};


#endif  // GRPC_ipc_5fconfigs_2eproto__INCLUDED
