// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc_configs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ipc_5fconfigs_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ipc_5fconfigs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ipc_5fconfigs_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ipc_5fconfigs_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_ipc_5fconfigs_2eproto;
class empty_return;
struct empty_returnDefaultTypeInternal;
extern empty_returnDefaultTypeInternal _empty_return_default_instance_;
class image_request;
struct image_requestDefaultTypeInternal;
extern image_requestDefaultTypeInternal _image_request_default_instance_;
class location_request;
struct location_requestDefaultTypeInternal;
extern location_requestDefaultTypeInternal _location_request_default_instance_;
class request_data;
struct request_dataDefaultTypeInternal;
extern request_dataDefaultTypeInternal _request_data_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template <>
::empty_return* Arena::CreateMaybeMessage<::empty_return>(Arena*);
template <>
::image_request* Arena::CreateMaybeMessage<::image_request>(Arena*);
template <>
::location_request* Arena::CreateMaybeMessage<::location_request>(Arena*);
template <>
::request_data* Arena::CreateMaybeMessage<::request_data>(Arena*);
PROTOBUF_NAMESPACE_CLOSE


// ===================================================================


// -------------------------------------------------------------------

class request_data final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:request_data) */ {
 public:
  inline request_data() : request_data(nullptr) {}
  ~request_data() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR request_data(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  request_data(const request_data& from);
  request_data(request_data&& from) noexcept
    : request_data() {
    *this = ::std::move(from);
  }

  inline request_data& operator=(const request_data& from) {
    CopyFrom(from);
    return *this;
  }
  inline request_data& operator=(request_data&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const request_data& default_instance() {
    return *internal_default_instance();
  }
  static inline const request_data* internal_default_instance() {
    return reinterpret_cast<const request_data*>(
               &_request_data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(request_data& a, request_data& b) {
    a.Swap(&b);
  }
  inline void Swap(request_data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(request_data* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  request_data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<request_data>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const request_data& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const request_data& from) {
    request_data::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(request_data* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "request_data";
  }
  protected:
  explicit request_data(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageDataFieldNumber = 1,
    kCarLocationFieldNumber = 2,
  };
  // .image_request image_data = 1;
  bool has_image_data() const;
  void clear_image_data() ;
  const ::image_request& image_data() const;
  PROTOBUF_NODISCARD ::image_request* release_image_data();
  ::image_request* mutable_image_data();
  void set_allocated_image_data(::image_request* image_data);
  private:
  const ::image_request& _internal_image_data() const;
  ::image_request* _internal_mutable_image_data();
  public:
  void unsafe_arena_set_allocated_image_data(
      ::image_request* image_data);
  ::image_request* unsafe_arena_release_image_data();
  // .location_request car_location = 2;
  bool has_car_location() const;
  void clear_car_location() ;
  const ::location_request& car_location() const;
  PROTOBUF_NODISCARD ::location_request* release_car_location();
  ::location_request* mutable_car_location();
  void set_allocated_car_location(::location_request* car_location);
  private:
  const ::location_request& _internal_car_location() const;
  ::location_request* _internal_mutable_car_location();
  public:
  void unsafe_arena_set_allocated_car_location(
      ::location_request* car_location);
  ::location_request* unsafe_arena_release_car_location();
  // @@protoc_insertion_point(class_scope:request_data)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::image_request* image_data_;
    ::location_request* car_location_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class image_request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:image_request) */ {
 public:
  inline image_request() : image_request(nullptr) {}
  ~image_request() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR image_request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  image_request(const image_request& from);
  image_request(image_request&& from) noexcept
    : image_request() {
    *this = ::std::move(from);
  }

  inline image_request& operator=(const image_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline image_request& operator=(image_request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const image_request& default_instance() {
    return *internal_default_instance();
  }
  static inline const image_request* internal_default_instance() {
    return reinterpret_cast<const image_request*>(
               &_image_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(image_request& a, image_request& b) {
    a.Swap(&b);
  }
  inline void Swap(image_request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(image_request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  image_request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<image_request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const image_request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const image_request& from) {
    image_request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(image_request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "image_request";
  }
  protected:
  explicit image_request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // bytes data = 1;
  void clear_data() ;
  const std::string& data() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* ptr);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:image_request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class location_request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:location_request) */ {
 public:
  inline location_request() : location_request(nullptr) {}
  ~location_request() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR location_request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  location_request(const location_request& from);
  location_request(location_request&& from) noexcept
    : location_request() {
    *this = ::std::move(from);
  }

  inline location_request& operator=(const location_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline location_request& operator=(location_request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const location_request& default_instance() {
    return *internal_default_instance();
  }
  static inline const location_request* internal_default_instance() {
    return reinterpret_cast<const location_request*>(
               &_location_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(location_request& a, location_request& b) {
    a.Swap(&b);
  }
  inline void Swap(location_request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(location_request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  location_request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<location_request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const location_request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const location_request& from) {
    location_request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(location_request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "location_request";
  }
  protected:
  explicit location_request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kPitchFieldNumber = 4,
    kYawFieldNumber = 5,
    kRollFieldNumber = 6,
  };
  // int32 x = 1;
  void clear_x() ;
  ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int32 y = 2;
  void clear_y() ;
  ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // int32 z = 3;
  void clear_z() ;
  ::int32_t z() const;
  void set_z(::int32_t value);

  private:
  ::int32_t _internal_z() const;
  void _internal_set_z(::int32_t value);

  public:
  // int32 pitch = 4;
  void clear_pitch() ;
  ::int32_t pitch() const;
  void set_pitch(::int32_t value);

  private:
  ::int32_t _internal_pitch() const;
  void _internal_set_pitch(::int32_t value);

  public:
  // int32 yaw = 5;
  void clear_yaw() ;
  ::int32_t yaw() const;
  void set_yaw(::int32_t value);

  private:
  ::int32_t _internal_yaw() const;
  void _internal_set_yaw(::int32_t value);

  public:
  // int32 roll = 6;
  void clear_roll() ;
  ::int32_t roll() const;
  void set_roll(::int32_t value);

  private:
  ::int32_t _internal_roll() const;
  void _internal_set_roll(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:location_request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::int32_t x_;
    ::int32_t y_;
    ::int32_t z_;
    ::int32_t pitch_;
    ::int32_t yaw_;
    ::int32_t roll_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};// -------------------------------------------------------------------

class empty_return final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:empty_return) */ {
 public:
  inline empty_return() : empty_return(nullptr) {}
  ~empty_return() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR empty_return(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  empty_return(const empty_return& from);
  empty_return(empty_return&& from) noexcept
    : empty_return() {
    *this = ::std::move(from);
  }

  inline empty_return& operator=(const empty_return& from) {
    CopyFrom(from);
    return *this;
  }
  inline empty_return& operator=(empty_return&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const empty_return& default_instance() {
    return *internal_default_instance();
  }
  static inline const empty_return* internal_default_instance() {
    return reinterpret_cast<const empty_return*>(
               &_empty_return_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(empty_return& a, empty_return& b) {
    a.Swap(&b);
  }
  inline void Swap(empty_return* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(empty_return* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  empty_return* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<empty_return>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const empty_return& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const empty_return& from) {
    empty_return::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(empty_return* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "empty_return";
  }
  protected:
  explicit empty_return(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // int32 result = 1;
  void clear_result() ;
  ::int32_t result() const;
  void set_result(::int32_t value);

  private:
  ::int32_t _internal_result() const;
  void _internal_set_result(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:empty_return)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::int32_t result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_5fconfigs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// request_data

// .image_request image_data = 1;
inline bool request_data::has_image_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.image_data_ != nullptr);
  return value;
}
inline void request_data::clear_image_data() {
  if (_impl_.image_data_ != nullptr) _impl_.image_data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::image_request& request_data::_internal_image_data() const {
  const ::image_request* p = _impl_.image_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::image_request&>(
      ::_image_request_default_instance_);
}
inline const ::image_request& request_data::image_data() const {
  // @@protoc_insertion_point(field_get:request_data.image_data)
  return _internal_image_data();
}
inline void request_data::unsafe_arena_set_allocated_image_data(
    ::image_request* image_data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.image_data_);
  }
  _impl_.image_data_ = image_data;
  if (image_data) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request_data.image_data)
}
inline ::image_request* request_data::release_image_data() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::image_request* temp = _impl_.image_data_;
  _impl_.image_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::image_request* request_data::unsafe_arena_release_image_data() {
  // @@protoc_insertion_point(field_release:request_data.image_data)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::image_request* temp = _impl_.image_data_;
  _impl_.image_data_ = nullptr;
  return temp;
}
inline ::image_request* request_data::_internal_mutable_image_data() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.image_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::image_request>(GetArenaForAllocation());
    _impl_.image_data_ = p;
  }
  return _impl_.image_data_;
}
inline ::image_request* request_data::mutable_image_data() {
  ::image_request* _msg = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:request_data.image_data)
  return _msg;
}
inline void request_data::set_allocated_image_data(::image_request* image_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.image_data_;
  }
  if (image_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(image_data);
    if (message_arena != submessage_arena) {
      image_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, image_data, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.image_data_ = image_data;
  // @@protoc_insertion_point(field_set_allocated:request_data.image_data)
}

// .location_request car_location = 2;
inline bool request_data::has_car_location() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.car_location_ != nullptr);
  return value;
}
inline void request_data::clear_car_location() {
  if (_impl_.car_location_ != nullptr) _impl_.car_location_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::location_request& request_data::_internal_car_location() const {
  const ::location_request* p = _impl_.car_location_;
  return p != nullptr ? *p : reinterpret_cast<const ::location_request&>(
      ::_location_request_default_instance_);
}
inline const ::location_request& request_data::car_location() const {
  // @@protoc_insertion_point(field_get:request_data.car_location)
  return _internal_car_location();
}
inline void request_data::unsafe_arena_set_allocated_car_location(
    ::location_request* car_location) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.car_location_);
  }
  _impl_.car_location_ = car_location;
  if (car_location) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request_data.car_location)
}
inline ::location_request* request_data::release_car_location() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::location_request* temp = _impl_.car_location_;
  _impl_.car_location_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::location_request* request_data::unsafe_arena_release_car_location() {
  // @@protoc_insertion_point(field_release:request_data.car_location)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::location_request* temp = _impl_.car_location_;
  _impl_.car_location_ = nullptr;
  return temp;
}
inline ::location_request* request_data::_internal_mutable_car_location() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.car_location_ == nullptr) {
    auto* p = CreateMaybeMessage<::location_request>(GetArenaForAllocation());
    _impl_.car_location_ = p;
  }
  return _impl_.car_location_;
}
inline ::location_request* request_data::mutable_car_location() {
  ::location_request* _msg = _internal_mutable_car_location();
  // @@protoc_insertion_point(field_mutable:request_data.car_location)
  return _msg;
}
inline void request_data::set_allocated_car_location(::location_request* car_location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.car_location_;
  }
  if (car_location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(car_location);
    if (message_arena != submessage_arena) {
      car_location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, car_location, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.car_location_ = car_location;
  // @@protoc_insertion_point(field_set_allocated:request_data.car_location)
}

// -------------------------------------------------------------------

// image_request

// bytes data = 1;
inline void image_request::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& image_request::data() const {
  // @@protoc_insertion_point(field_get:image_request.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void image_request::set_data(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:image_request.data)
}
inline std::string* image_request::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:image_request.data)
  return _s;
}
inline const std::string& image_request::_internal_data() const {
  return _impl_.data_.Get();
}
inline void image_request::_internal_set_data(const std::string& value) {
  ;


  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* image_request::_internal_mutable_data() {
  ;
  return _impl_.data_.Mutable( GetArenaForAllocation());
}
inline std::string* image_request::release_data() {
  // @@protoc_insertion_point(field_release:image_request.data)
  return _impl_.data_.Release();
}
inline void image_request::set_allocated_data(std::string* value) {
  _impl_.data_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:image_request.data)
}

// -------------------------------------------------------------------

// location_request

// int32 x = 1;
inline void location_request::clear_x() {
  _impl_.x_ = 0;
}
inline ::int32_t location_request::x() const {
  // @@protoc_insertion_point(field_get:location_request.x)
  return _internal_x();
}
inline void location_request::set_x(::int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:location_request.x)
}
inline ::int32_t location_request::_internal_x() const {
  return _impl_.x_;
}
inline void location_request::_internal_set_x(::int32_t value) {
  ;
  _impl_.x_ = value;
}

// int32 y = 2;
inline void location_request::clear_y() {
  _impl_.y_ = 0;
}
inline ::int32_t location_request::y() const {
  // @@protoc_insertion_point(field_get:location_request.y)
  return _internal_y();
}
inline void location_request::set_y(::int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:location_request.y)
}
inline ::int32_t location_request::_internal_y() const {
  return _impl_.y_;
}
inline void location_request::_internal_set_y(::int32_t value) {
  ;
  _impl_.y_ = value;
}

// int32 z = 3;
inline void location_request::clear_z() {
  _impl_.z_ = 0;
}
inline ::int32_t location_request::z() const {
  // @@protoc_insertion_point(field_get:location_request.z)
  return _internal_z();
}
inline void location_request::set_z(::int32_t value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:location_request.z)
}
inline ::int32_t location_request::_internal_z() const {
  return _impl_.z_;
}
inline void location_request::_internal_set_z(::int32_t value) {
  ;
  _impl_.z_ = value;
}

// int32 pitch = 4;
inline void location_request::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline ::int32_t location_request::pitch() const {
  // @@protoc_insertion_point(field_get:location_request.pitch)
  return _internal_pitch();
}
inline void location_request::set_pitch(::int32_t value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:location_request.pitch)
}
inline ::int32_t location_request::_internal_pitch() const {
  return _impl_.pitch_;
}
inline void location_request::_internal_set_pitch(::int32_t value) {
  ;
  _impl_.pitch_ = value;
}

// int32 yaw = 5;
inline void location_request::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline ::int32_t location_request::yaw() const {
  // @@protoc_insertion_point(field_get:location_request.yaw)
  return _internal_yaw();
}
inline void location_request::set_yaw(::int32_t value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:location_request.yaw)
}
inline ::int32_t location_request::_internal_yaw() const {
  return _impl_.yaw_;
}
inline void location_request::_internal_set_yaw(::int32_t value) {
  ;
  _impl_.yaw_ = value;
}

// int32 roll = 6;
inline void location_request::clear_roll() {
  _impl_.roll_ = 0;
}
inline ::int32_t location_request::roll() const {
  // @@protoc_insertion_point(field_get:location_request.roll)
  return _internal_roll();
}
inline void location_request::set_roll(::int32_t value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:location_request.roll)
}
inline ::int32_t location_request::_internal_roll() const {
  return _impl_.roll_;
}
inline void location_request::_internal_set_roll(::int32_t value) {
  ;
  _impl_.roll_ = value;
}

// -------------------------------------------------------------------

// empty_return

// int32 result = 1;
inline void empty_return::clear_result() {
  _impl_.result_ = 0;
}
inline ::int32_t empty_return::result() const {
  // @@protoc_insertion_point(field_get:empty_return.result)
  return _internal_result();
}
inline void empty_return::set_result(::int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:empty_return.result)
}
inline ::int32_t empty_return::_internal_result() const {
  return _impl_.result_;
}
inline void empty_return::_internal_set_result(::int32_t value) {
  ;
  _impl_.result_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ipc_5fconfigs_2eproto_2epb_2eh
