name: grpc_test

on:
  push:
    branches:
      - main
      - Dev
      - Test/grpc_test

jobs:
  build:
    runs-on: windows-latest  # Use the Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache CMake dependencies
        uses: actions/cache@v2
        with:
          path: |
            D:\a\Self-Parking-Car/build
          key: |
            Windows--build

      - name: Install NASM
        run: |
          choco install nasm

      - name: Build project
        run: |
            PowerShell.exe -ExecutionPolicy Bypass -File ipc_build.ps1

      - name: Run grpc tests
        run: |
          ./src/build/grpc_test.exe
