name: grpc_test

on:
  push:
    branches:
      - main
      - Dev
      - Test/grpc_test

jobs:
  build:
    runs-on: windows-latest  # Use the Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NASM Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: nasm-windows

      - name: Check if NASM is cached
        id: check-cache
        run: |
          if [ -x ~/.cache/nasm ]; then
            echo "::set-output name=nasm-cache-exists::true"
          else
            echo "::set-output name=nasm-cache-exists::false"
          fi
        shell: bash

      - name: Install NASM
        if: steps.check-cache.outputs.nasm-cache-exists != 'true'
        run: |
          choco install nasm

      - name: Cache NASM
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: nasm-windows

      - name: Restore cache CMake configuration
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cmake-cache

      - name: Build project
        run: |
            PowerShell.exe -ExecutionPolicy Bypass -File ipc_build.ps1

      - name: Cache CMake output
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cmake-cache

      # - name: Run grpc tests
      #   run: |
      #     ./src/build/grpc_test.exe
