name: grpc_pre_setup

on:
  push:
    branches:
      - main
      - Dev
      - Test/grpc_test

jobs:
  build:
    runs-on: windows-latest  # Use the Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NASM build from cache
        uses: actions/cache@v2
        id: restore_nasm_cache
        with:
          path: ~/.nasm_cache
          key: nasm_cache

      - name: Check if NASM is cached
        id: check-cache
        run: |
          if [[ "${{ steps.restore_nasm_cache.outputs.cache-hit }}" == 'true' ]]; then
            echo "NASM_CACHE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "NASM_CACHE_EXISTS=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Install NASM
        if: env.NASM_CACHE_EXISTS != 'true'
        run: |
          choco install nasm

      - name: Cache NASM build
        uses: actions/cache@v2
        with:
          path: ~/.nasm_cache
          key: nasm_cache